#include <vector>;
using namespace std;
int input();
vector<vector<int>> generationSquare(vector<vector<int>> matrix, int n, int m);
bool checkCorrectSquare(vector<vector<int>> matrix, int m);
void outputSumm();
void outputToFile();
int loadFromFile();
void game();
void outputMatrix(vector<vector<int>> matrix);
vector<vector<int>> generationPlayersSquare(vector<vector<int>> matrix, int m);
void playersMove(vector<vector<int>>& matrix, vector <int>& moves);
vector <int> possibleMoves(vector<vector<int>> matrix, vector<vector<int>> player_matrix, int m);
void outputVector(vector<int> moves);
vector <int> deleteUsedMove(vector <int> moves, int number);